<a href="https://colab.research.google.com/github/supatsara2002/bsc_dpdm22/blob/main/Performance_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [706]:
from sklearn import datasets
iris_data = datasets.load_iris()

In [707]:
X = iris_data['data']
y = iris_data['target']

In [708]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold, cross_val_score

In [709]:
model = DecisionTreeClassifier()

# Define the cross-validation strategy
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform cross-validation and get the accuracy scores
scores = cross_val_score(model, X, y, cv=kf)

# Compute the average accuracy score and print it
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.10)

In [710]:
from sklearn.model_selection import LeaveOneOut

In [711]:
model = DecisionTreeClassifier()

# Define the cross-validation strategy
LOO = LeaveOneOut()

# Perform cross-validation and get the accuracy scores
scores = cross_val_score(model, X, y, cv=LOO)

# Compute the average accuracy score and print it
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.42)

In [712]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

transform numpy array to dataframe

In [713]:
import pandas as pd

In [714]:
columns = iris_data['feature_names']

In [715]:
columns = iris_data['feature_names']
X_df = pd.DataFrame(X, columns=columns)
X_df['label']=y
shuffled_df = X_df.sample(frac=1,random_state=6)
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]

In [716]:
X_df = pd.DataFrame(X, columns=columns)
X_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [717]:
X_df['label']=y

In [718]:
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [719]:
shuffled_df = X_df.sample(frac=1,random_state=6)
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
116,6.5,3.0,5.5,1.8,2
2,4.7,3.2,1.3,0.2,0
23,5.1,3.3,1.7,0.5,0
123,6.3,2.7,4.9,1.8,2
...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2
79,5.7,2.6,3.5,1.0,1
109,7.2,3.6,6.1,2.5,2
106,4.9,2.5,4.5,1.7,2
138,6.0,3.0,4.8,1.8,2

In [720]:
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]

In [721]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

#HW6 วนลูปทำ 10-fold cross validation

In [722]:
shuffled_df = shuffled_df.sort_values('fold')

In [723]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
83,6.0,2.7,5.1,1.6,1,1
98,5.1,2.5,3.0,1.1,1,1
118,7.7,2.6,6.9,2.3,2,1
76,6.8,2.8,4.8,1.4,1,1
...,...,...,...,...,...,...
93,5.0,2.3,3.3,1.0,1,10
114,5.8,2.8,5.1,2.4,2,10
57,4.9,2.4,3.3,1.0,1,10
77,6.7,3.0,5.0,1.7,1,10
138,6.0,3.0,4.8,1.8,2,10

In [726]:
# Define the number of folds
n_folds = 10

# Split the data into features and target
X = shuffled_df.drop('label', axis=1)
y = shuffled_df['label']

# Define a cross-validation object with the specified number of folds
kfold = KFold(n_splits=n_folds)

# Loop over the folds
for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y)):
    # Get the training and testing data for the current fold
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_test, y_test = X.iloc[test_idx], y.iloc[test_idx]
    
    # Create a decision tree classifier object
    dtc = DecisionTreeClassifier()
    
    # Fit the model on the training data
    dtc.fit(X_train, y_train)
    
    # Evaluate the model on the testing data
    scores = cross_val_score(dtc, X_test, y_test, cv=kfold)
    
    # Print the cross-validation score and the data for the current fold
    print(f"Fold: {fold+1}")
    print("Mean accuracy: %0.2f (+/- %0.2f)" % (np.mean(scores), np.std(scores) * 2))
    print(shuffled_df[shuffled_df['fold'] == fold+1])
    print()

Fold: 1
Mean accuracy: 0.85 (+/- 0.64)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
4                  5.0               3.6                1.4               0.2
83                 6.0               2.7                5.1               1.6
98                 5.1               2.5                3.0               1.1
118                7.7               2.6                6.9               2.3
76                 6.8               2.8                4.8               1.4
41                 4.5               2.3                1.3               0.3
17                 5.1               3.5                1.4               0.3
90                 5.5               2.6                4.4               1.2
45                 4.8               3.0                1.4               0.3
43                 5.0               3.5                1.6               0.6
37                 4.9               3.6                1.4               0.1
86                 6.7               3.1                4.7               1.5
89                 5.5               2.5                4.0               1.3
127                6.1               3.0                4.9               1.8
75                 6.6               3.0                4.4               1.4

     label  fold
4        0     1
83       1     1
98       1     1
118      2     1
76       1     1
41       0     1
17       0     1
90       1     1
45       0     1
43       0     1
37       0     1
86       1     1
89       1     1
127      2     1
75       1     1

Fold: 2
Mean accuracy: 0.95 (+/- 0.30)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
22                 4.6               3.6                1.0               0.2
117                7.7               3.8                6.7               2.2
103                6.3               2.9                5.6               1.8
9                  4.9               3.1                1.5               0.1
1                  4.9               3.0                1.4               0.2
145                6.7               3.0                5.2               2.3
84                 5.4               3.0                4.5               1.5
33                 5.5               4.2                1.4               0.2
116                6.5               3.0                5.5               1.8
28                 5.2               3.4                1.4               0.2
59                 5.2               2.7                3.9               1.4
60                 5.0               2.0                3.5               1.0
120                6.9               3.2                5.7               2.3
81                 5.5               2.4                3.7               1.0
15                 5.7               4.4                1.5               0.4

     label  fold
22       0     2
117      2     2
103      2     2
9        0     2
1        0     2
145      2     2
84       1     2
33       0     2
116      2     2
28       0     2
59       1     2
60       1     2
120      2     2
81       1     2
15       0     2

Fold: 3
Mean accuracy: 0.75 (+/- 0.81)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
56                 6.3               3.3                4.7               1.6
142                5.8               2.7                5.1               1.9
121                5.6               2.8                4.9               2.0
71                 6.1               2.8                4.0               1.3
125                7.2               3.2                6.0               1.8
25                 5.0               3.0                1.6               0.2
115                6.4               3.2                5.3               2.3
35                 5.0               3.2                1.2               0.2
104                6.5               3.0                5.8               2.2
99                 5.7               2.8                4.1               1.3
16                 5.4               3.9                1.3               0.4
44                 5.1               3.8                1.9               0.4
70                 5.9               3.2                4.8               1.8
2                  4.7               3.2                1.3               0.2
85                 6.0               3.4                4.5               1.6

     label  fold
56       1     3
142      2     3
121      2     3
71       1     3
125      2     3
25       0     3
115      2     3
35       0     3
104      2     3
99       1     3
16       0     3
44       0     3
70       1     3
2        0     3
85       1     3

Fold: 4
Mean accuracy: 0.80 (+/- 0.80)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5
112                6.8               3.0                5.5               2.1
6                  4.6               3.4                1.4               0.3
132                6.4               2.8                5.6               2.2
23                 5.1               3.3                1.7               0.5
135                7.7               3.0                6.1               2.3
140                6.7               3.1                5.6               2.4
62                 6.0               2.2                4.0               1.0
61                 5.9               3.0                4.2               1.5
82                 5.8               2.7                3.9               1.2
69                 5.6               2.5                3.9               1.1
0                  5.1               3.5                1.4               0.2
19                 5.1               3.8                1.5               0.3
31                 5.4               3.4                1.5               0.4
13                 4.3               3.0                1.1               0.1

     label  fold
100      2     4
112      2     4
6        0     4
132      2     4
23       0     4
135      2     4
140      2     4
62       1     4
61       1     4
82       1     4
69       1     4
0        0     4
19       0     4
31       0     4
13       0     4

Fold: 5
Mean accuracy: 0.85 (+/- 0.64)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
36                 5.5               3.5                1.3               0.2
21                 5.1               3.7                1.5               0.4
141                6.9               3.1                5.1               2.3
40                 5.0               3.5                1.3               0.3
130                7.4               2.8                6.1               1.9
63                 6.1               2.9                4.7               1.4
80                 5.5               2.4                3.8               1.1
147                6.5               3.0                5.2               2.0
133                6.3               2.8                5.1               1.5
94                 5.6               2.7                4.2               1.3
74                 6.4               2.9                4.3               1.3
46                 5.1               3.8                1.6               0.2
123                6.3               2.7                4.9               1.8
55                 5.7               2.8                4.5               1.3
111                6.4               2.7                5.3               1.9

     label  fold
36       0     5
21       0     5
141      2     5
40       0     5
130      2     5
63       1     5
80       1     5
147      2     5
133      2     5
94       1     5
74       1     5
46       0     5
123      2     5
55       1     5
111      2     5

Fold: 6
Mean accuracy: 0.70 (+/- 0.66)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
7                  5.0               3.4                1.5               0.2
72                 6.3               2.5                4.9               1.5
78                 6.0               2.9                4.5               1.5
128                6.4               2.8                5.6               2.1
11                 4.8               3.4                1.6               0.2
119                6.0               2.2                5.0               1.5
8                  4.4               2.9                1.4               0.2
12                 4.8               3.0                1.4               0.1
47                 4.6               3.2                1.4               0.2
126                6.2               2.8                4.8               1.8
88                 5.6               3.0                4.1               1.3
148                6.2               3.4                5.4               2.3
18                 5.7               3.8                1.7               0.3
65                 6.7               3.1                4.4               1.4
96                 5.7               2.9                4.2               1.3

     label  fold
7        0     6
72       1     6
78       1     6
128      2     6
11       0     6
119      2     6
8        0     6
12       0     6
47       0     6
126      2     6
88       1     6
148      2     6
18       0     6
65       1     6
96       1     6

Fold: 7
Mean accuracy: 0.70 (+/- 0.92)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
38                 4.4               3.0                1.3               0.2
87                 6.3               2.3                4.4               1.3
66                 5.6               3.0                4.5               1.5
149                5.9               3.0                5.1               1.8
3                  4.6               3.1                1.5               0.2
79                 5.7               2.6                3.5               1.0
105                7.6               3.0                6.6               2.1
122                7.7               2.8                6.7               2.0
73                 6.1               2.8                4.7               1.2
64                 5.6               2.9                3.6               1.3
107                7.3               2.9                6.3               1.8
134                6.1               2.6                5.6               1.4
113                5.7               2.5                5.0               2.0
52                 6.9               3.1                4.9               1.5
68                 6.2               2.2                4.5               1.5

     label  fold
38       0     7
87       1     7
66       1     7
149      2     7
3        0     7
79       1     7
105      2     7
122      2     7
73       1     7
64       1     7
107      2     7
134      2     7
113      2     7
52       1     7
68       1     7

Fold: 8
Mean accuracy: 1.00 (+/- 0.00)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
139                6.9               3.1                5.4               2.1
50                 7.0               3.2                4.7               1.4
39                 5.1               3.4                1.5               0.2
102                7.1               3.0                5.9               2.1
109                7.2               3.6                6.1               2.5
51                 6.4               3.2                4.5               1.5
27                 5.2               3.5                1.5               0.2
144                6.7               3.3                5.7               2.5
101                5.8               2.7                5.1               1.9
67                 5.8               2.7                4.1               1.0
20                 5.4               3.4                1.7               0.2
146                6.3               2.5                5.0               1.9
42                 4.4               3.2                1.3               0.2
110                6.5               3.2                5.1               2.0
131                7.9               3.8                6.4               2.0

     label  fold
139      2     8
50       1     8
39       0     8
102      2     8
109      2     8
51       1     8
27       0     8
144      2     8
101      2     8
67       1     8
20       0     8
146      2     8
42       0     8
110      2     8
131      2     8

Fold: 9
Mean accuracy: 0.90 (+/- 0.60)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
26                 5.0               3.4                1.6               0.4
143                6.8               3.2                5.9               2.3
137                6.4               3.1                5.5               1.8
14                 5.8               4.0                1.2               0.2
10                 5.4               3.7                1.5               0.2
34                 4.9               3.1                1.5               0.2
5                  5.4               3.9                1.7               0.4
30                 4.8               3.1                1.6               0.2
106                4.9               2.5                4.5               1.7
129                7.2               3.0                5.8               1.6
95                 5.7               3.0                4.2               1.2
58                 6.6               2.9                4.6               1.3
91                 6.1               3.0                4.6               1.4
48                 5.3               3.7                1.5               0.2
92                 5.8               2.6                4.0               1.2

     label  fold
26       0     9
143      2     9
137      2     9
14       0     9
10       0     9
34       0     9
5        0     9
30       0     9
106      2     9
129      2     9
95       1     9
58       1     9
91       1     9
48       0     9
92       1     9

Fold: 10
Mean accuracy: 0.90 (+/- 0.60)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
29                 4.7               3.2                1.6               0.2
108                6.7               2.5                5.8               1.8
97                 6.2               2.9                4.3               1.3
136                6.3               3.4                5.6               2.4
32                 5.2               4.1                1.5               0.1
54                 6.5               2.8                4.6               1.5
24                 4.8               3.4                1.9               0.2
53                 5.5               2.3                4.0               1.3
49                 5.0               3.3                1.4               0.2
124                6.7               3.3                5.7               2.1
93                 5.0               2.3                3.3               1.0
114                5.8               2.8                5.1               2.4
57                 4.9               2.4                3.3               1.0
77                 6.7               3.0                5.0               1.7
138                6.0               3.0                4.8               1.8

     label  fold
29       0    10
108      2    10
97       1    10
136      2    10
32       0    10
54       1    10
24       0    10
53       1    10
49       0    10
124      2    10
93       1    10
114      2    10
57       1    10
77       1    10
138      2    10